repositories {
        maven {
            url = "https://maven.firstdark.dev/snapshots"
        }
    }
    dependencies {
       implementation("com.lowdragmc.ldlib2:ldlib2-neoforge-1.21.1:2.2.8:all") { transitive = false }
       compileOnly("org.appliedenergistics.yoga:yoga:1.0.0")
       implementation("com.lowdragmc.photon:photon-neoforge-1.21.1:2.1.4") { transitive = false }
    }


